import Image from "next/image";
import { ArrowRight, ArrowUpRight, Database, Layers3, ScanLine } from "lucide-react";
import { slides } from "./content";

export function Device({ type = "desktop" }: { type?: "desktop" | "tablet" | "phone" }) {
  return <div className={`device device-${type}`}>
    <div className="device-screen"><Image src={`/presentation/clark-${type}.png`} alt={`Clark County assistant, actual ${type} interface capture`} width={type === "desktop" ? 1440 : type === "tablet" ? 820 : 390} height={type === "desktop" ? 1000 : type === "tablet" ? 1100 : 844} unoptimized /></div>
    {type === "desktop" && <div className="device-foot" />}
  </div>;
}

function Heading({ eyebrow, title, description }: { eyebrow: string; title: string; description?: string }) {
  return <div className="slide-heading"><p className="eyebrow">{eyebrow}</p><h2>{title}</h2>{description && <p className="slide-description">{description}</p>}</div>;
}

export function Slide({ index }: { index: number }) {
  const slide = slides[index];
  return <article className={`deck-slide slide-${slide.kind}`} aria-label={`Slide ${index + 1}: ${slide.title}`}>
    <div className="slide-top"><span>HR&A <span className="brand-divider">/</span> Tech & Society</span><span>{slide.chapter}</span></div>
    {slide.kind === "cover" && <div className="cover-layout"><div className="cover-copy"><p className="eyebrow">The product development practice</p><h1>Public purpose.<br /><span>Product thinking.</span></h1><p>Turning deep expertise into<br />tools people can use.</p><div className="cover-credit">A closer look at digital equity<br /><strong>Clark County, Nevada</strong></div></div><div className="cover-visual"><div className="visual-caption">BUILT AROUND REAL PEOPLE</div><Device /><div className="cover-phone"><Device type="phone" /></div></div></div>}
    {slide.kind === "studio" && <><Heading eyebrow="Tech & Society + digital product expertise" title={slide.title} /><div className="studio-layout"><p className="statement">We connect <em>policy,<br />data, and design</em><br />to public purpose.</p><div className="studio-copy"><p>HR&A helps public-interest organizations navigate technological change and turn it into community opportunity.</p><div className="word-list"><span>Public-sector strategy</span><span>Rigorous data analysis</span><span>Custom digital tools</span></div><p className="quiet">For governments, institutions, philanthropies, and their partners.</p></div></div></>}
    {slide.kind === "why" && <><Heading eyebrow="Domain expertise comes first" title={slide.title} /><div className="proof-grid"><div><span className="location">New York</span><h3>From investment<br />to implementation.</h3><p>Strategic advisory and program management for ConnectALL.</p></div><div><span className="location">Texas</span><h3>From ambition<br />to a statewide plan.</h3><p>Development of the State’s first Digital Opportunity Plan.</p></div><div><span className="location">Rhode Island</span><h3>From fragmented data<br />to shared insight.</h3><p>Standardized land use datasets across 39 municipalities.</p></div></div><p className="bottom-thought">The tool starts with understanding the work.</p></>}
    {slide.kind === "framework" && <><Heading eyebrow="A proposed delivery framework" title={slide.title} /><div className="framework-stack"><div><ScanLine /><h3>Experience</h3><p>Make the next step clear.</p><span>Frontend</span></div><div><Layers3 /><h3>Intelligence</h3><p>Connect needs to relevant options.</p><span>Application logic</span></div><div><Database /><h3>Evidence</h3><p>Give every answer a foundation.</p><span>Data</span></div></div><p className="bottom-thought">Designed together. Not assembled in isolation.</p></>}
    {slide.kind === "data" && <><Heading eyebrow="Expert-led data design" title={slide.title} description="Analysts and subject-matter experts make the data useful before the interface makes it simple." /><div className="data-process">{[{n:"01",t:"Source",d:"Find the right evidence."},{n:"02",t:"Structure",d:"Define what matters."},{n:"03",t:"Check",d:"Review quality and gaps."},{n:"04",t:"Steward",d:"Assign owners and updates."}].map(x=><div key={x.n}><span>{x.n}</span><h3>{x.t}</h3><p>{x.d}</p></div>)}</div><div className="data-proof"><strong>Analytical depth, made practical.</strong><p>HR&A Labs combines rigorous data analysis, data science, and custom data solutions.</p></div><p className="slide-fine">Proposed QA and stewardship model. Scope and responsibilities agreed with each client.</p></>}
    {slide.kind === "delivery" && <><Heading eyebrow="Recommended engagement model" title={slide.title} /><div className="delivery-path">{[{t:"Discover",d:"Understand the people and the decision."},{t:"Build",d:"Shape the data and the experience."},{t:"Validate",d:"Test with users. Review with experts."},{t:"Sustain",d:"Train the team. Keep information useful."}].map((x,i)=><div key={x.t}><span className="step-index">0{i+1}</span><h3>{x.t}</h3><p>{x.d}</p>{i<3 && <ArrowRight aria-hidden="true" />}</div>)}</div><div className="delivery-outcome"><span>Design for adoption.</span><span>Measure usefulness.</span><span>Plan for change.</span></div></>}
    {slide.kind === "product" && <div className="product-layout"><div><p className="eyebrow">Introducing the public service navigator</p><h2>A clearer path<br />to getting<br /><span>connected.</span></h2><p className="slide-description">The Clark County<br />Digital Equity Assistant</p><div className="product-tags"><span>Internet</span><span>Skills</span><span>Devices</span></div></div><div className="product-device"><Device type="tablet" /></div></div>}
    {slide.kind === "devices" && <><Heading eyebrow="One responsive experience" title={slide.title} /><div className="device-lineup"><figure><Device /><figcaption><strong>Desktop</strong><span>At the service desk</span></figcaption></figure><figure><Device type="tablet" /><figcaption><strong>Tablet</strong><span>Side by side</span></figcaption></figure><figure><Device type="phone" /><figcaption><strong>Phone</strong><span>Out in the community</span></figcaption></figure></div></>}
    {slide.kind === "features" && <><Heading eyebrow="An intentional frontend" title={slide.title} /><div className="feature-layout"><div className="feature-capture"><Image src="/presentation/clark-desktop.png" width={1440} height={1000} alt="Clark County home screen showing language selection, task choices, and how-it-works instructions" unoptimized /><span className="capture-marker marker-one">1</span><span className="capture-marker marker-two">2</span><span className="capture-marker marker-three">3</span></div><ol className="feature-list"><li><span>1</span><div><h3>A familiar starting point.</h3><p>Choose a task, not a perfect prompt.</p></div></li><li><span>2</span><div><h3>A choice of language.</h3><p>English and Spanish interface options.</p></div></li><li><span>3</span><div><h3>A visible next step.</h3><p>Explain the journey before asking for an address.</p></div></li></ol></div></>}
    {slide.kind === "logic" && <><Heading eyebrow="The data layer in this build" title={slide.title} /><div className="logic-flow"><div><p className="eyebrow">Input</p><h3>A resident’s<br />location and need.</h3></div><ArrowRight aria-hidden="true" /><div className="logic-core"><p className="eyebrow">Structured lookup</p><h3>Address records<br />Broadband plan rules<br />Resource directory</h3></div><ArrowRight aria-hidden="true" /><div><p className="eyebrow">Output</p><h3>Relevant options.<br />A way to act.</h3></div></div><p className="bottom-thought">Conversation is the interface. Data does the matching.</p><p className="slide-fine">Availability, price, and eligibility must be confirmed with the provider.</p></>}
    {slide.kind === "adapt" && <><Heading eyebrow="Beyond digital equity · potential adaptations" title={slide.title} /><div className="adapt-layout"><div className="adapt-core"><p className="eyebrow">Public Service Navigator</p><h3>Keep the<br />experience.<br /><span>Tailor the<br />intelligence.</span></h3></div><div className="adapt-options"><div><h3>Housing resources</h3><p>Local programs. Clear referral pathways.</p></div><div><h3>Workforce & training</h3><p>Relevant opportunities. Practical next steps.</p></div><div><h3>Small-business support</h3><p>Program discovery. Local requirements.</p></div></div></div><p className="slide-fine">Working product-category name. Each adaptation requires new data, validation, training, and a scoped maintenance plan.</p></>}
    {slide.kind === "closing" && <div className="closing-layout"><div><p className="eyebrow">See the Clark County assistant</p><h2>From a question<br />to a <span>next step.</span></h2><p className="slide-description">A local tool.<br />A transferable approach.</p><a className="demo-link" href="/" target="_blank" rel="noreferrer">Open the live demo <ArrowUpRight size={20} /></a><p className="demo-note">Opens the current build in a new tab.</p></div><div className="closing-device"><Device type="phone" /></div></div>}
    <div className="slide-bottom"><span>Tech & Society <span className="brand-divider">/</span> Digital products</span><span>{String(index+1).padStart(2,"0")}</span></div>
  </article>;
}
